### PR TITLE
Add a test for update command

### PR DESCRIPTION
**Pull request by purbon**
In https://github.com/elastic/logstash/issues/3678 there has been a report about the plugin manager not working properly doing update after removing a plugin, because the internal cache was still filed with stale gems.

This PR add a test for this situation.

### CODE REVIEW

**Comment by ph** [comment]
I'll look into asap!

**Comment by purbon** [comment]
@ph any good luck getting this in? does it does what I expect it to do :) thanks for your time man!

**Comment by ph** [comment]
the test just hang on me, doesnt pass:

```
  update
         update after a plugin remove
```

**Comment by purbon** [comment]
Any idea why it could be hanging?

**Comment by ph** [comment]
o_O it perfectly run the second time.

**Comment by purbon** [comment]
what? what do you think could have happen to have this strange behaviour?

**Comment by ph** [comment]
Ma machine was having bad hair day, I run the test mutliples times the update are really slow.

LGTM.

**Pull request closed without merging**
